CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS emprestimos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    emp_data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    emp_user INTEGER NOT NULL,
    emp_book INTEGER NOT NULL,
    FOREIGN KEY(emp_user) REFERENCES books(user_id),
    FOREIGN KEY(emp_book) REFERENCES books(id)
);
